package bench.accessor;

import bench.paths.beans.Address;
import bench.paths.beans.Bool5;
import bench.paths.beans.Car;
import bench.paths.beans.ExtPerson;
import bench.paths.beans.Int5;
import bench.paths.beans.Str1;
import bench.paths.beans.Str5;

/**
 * Hand-written stand-ins for the Gizmo-generated per-bean accessors: a switch on the property index
 * to a direct field read, which is what the generated bytecode does.
 */
public final class Accessors {

    private Accessors() {
    }

    public static final class Str1Accessor extends PropertyAccessor {
        @Override
        public String stringGetter(Object bean, int index) {
            Str1 b = (Str1) bean;
            switch (index) {
                case 0: return b.p0;
                default: throw new IllegalArgumentException();
            }
        }

        @Override
        public int indexOf(String memberName) {
            return "p0".equals(memberName) ? 0 : -1;
        }
    }

    public static final class Str5Accessor extends PropertyAccessor {
        @Override
        public String stringGetter(Object bean, int index) {
            Str5 b = (Str5) bean;
            switch (index) {
                case 0: return b.p0;
                case 1: return b.p1;
                case 2: return b.p2;
                case 3: return b.p3;
                case 4: return b.p4;
                default: throw new IllegalArgumentException();
            }
        }

        @Override
        public int indexOf(String memberName) {
            switch (memberName) {
                case "p0": return 0;
                case "p1": return 1;
                case "p2": return 2;
                case "p3": return 3;
                case "p4": return 4;
                default: return -1;
            }
        }
    }

    public static final class Int5Accessor extends PropertyAccessor {
        @Override
        public int intGetter(Object bean, int index) {
            Int5 b = (Int5) bean;
            switch (index) {
                case 0: return b.p0;
                case 1: return b.p1;
                case 2: return b.p2;
                case 3: return b.p3;
                case 4: return b.p4;
                default: throw new IllegalArgumentException();
            }
        }

        @Override
        public int indexOf(String memberName) {
            switch (memberName) {
                case "p0": return 0;
                case "p1": return 1;
                case "p2": return 2;
                case "p3": return 3;
                case "p4": return 4;
                default: return -1;
            }
        }
    }

    public static final class Bool5Accessor extends PropertyAccessor {
        @Override
        public boolean booleanGetter(Object bean, int index) {
            Bool5 b = (Bool5) bean;
            switch (index) {
                case 0: return b.p0;
                case 1: return b.p1;
                case 2: return b.p2;
                case 3: return b.p3;
                case 4: return b.p4;
                default: throw new IllegalArgumentException();
            }
        }

        @Override
        public int indexOf(String memberName) {
            switch (memberName) {
                case "p0": return 0;
                case "p1": return 1;
                case "p2": return 2;
                case "p3": return 3;
                case "p4": return 4;
                default: return -1;
            }
        }
    }

    /** The end-to-end bean: two Strings, an int, and two nested beans. */
    public static final class ExtPersonAccessor extends PropertyAccessor {
        @Override
        public String stringGetter(Object bean, int index) {
            ExtPerson b = (ExtPerson) bean;
            switch (index) {
                case 0: return b.firstName;
                case 1: return b.lastName;
                default: throw new IllegalArgumentException();
            }
        }

        @Override
        public int intGetter(Object bean, int index) {
            ExtPerson b = (ExtPerson) bean;
            if (index == 2) {
                return b.age;
            }
            throw new IllegalArgumentException();
        }

        @Override
        public Object objectGetter(Object bean, int index) {
            ExtPerson b = (ExtPerson) bean;
            switch (index) {
                case 3: return b.address;
                case 4: return b.car;
                default: throw new IllegalArgumentException();
            }
        }

        @Override
        public int indexOf(String memberName) {
            switch (memberName) {
                case "firstName": return 0;
                case "lastName": return 1;
                case "age": return 2;
                case "address": return 3;
                case "car": return 4;
                default: return -1;
            }
        }
    }

    public static final class AddressAccessor extends PropertyAccessor {
        @Override
        public String stringGetter(Object bean, int index) {
            Address b = (Address) bean;
            switch (index) {
                case 0: return b.city;
                case 1: return b.street;
                default: throw new IllegalArgumentException();
            }
        }

        @Override
        public int indexOf(String memberName) {
            switch (memberName) {
                case "city": return 0;
                case "street": return 1;
                default: return -1;
            }
        }
    }

    public static final class CarAccessor extends PropertyAccessor {
        @Override
        public String stringGetter(Object bean, int index) {
            Car b = (Car) bean;
            switch (index) {
                case 0: return b.brand;
                case 1: return b.model;
                default: throw new IllegalArgumentException();
            }
        }

        @Override
        public int indexOf(String memberName) {
            switch (memberName) {
                case "brand": return 0;
                case "model": return 1;
                default: return -1;
            }
        }
    }
}
