package bench.paths;

import java.io.IOException;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import tools.jackson.databind.ObjectWriter;
import tools.jackson.databind.module.SimpleModule;

import org.openjdk.jmh.annotations.*;

import bench.Sink;
import bench.paths.accessor.*;
import bench.paths.beans.Address;
import bench.paths.beans.Car;
import bench.paths.beans.ExtendedPerson;

/**
 * The per-bean property-accessor design (Quarkus branch perf/pb-accessor-on-main, commit
 * 7bab6dfe1e9): Jackson's own UnrolledBeanSerializer, with every plain BeanPropertyWriter replaced
 * by a type-specialised GeneratedPropertyWriter that reads the value through a generated per-bean
 * accessor (accessor.stringGetter(bean, index)) instead of a MethodHandle. Runtime classes are
 * verbatim copies; the accessors are transcribed from the generated bytecode. Registered as
 * GeneratedPropertyAccessorRegister does: a SimpleModule with the serializer modifier.
 */
@State(Scope.Benchmark)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@Fork(value = 3, jvmArgs = { "-Xms1g", "-Xmx1g", "-XX:+UseParallelGC", "-XX:+AlwaysPreTouch" })
@Warmup(iterations = 5, time = 1)
@Measurement(iterations = 5, time = 1)
@Threads(1)
public class AccessorBench {

    @Param("0")
    public int strLen;

    /**
     * typed = the branch's six writer classes; kind = one KindWriter class switching on an int kind;
     * direct = one writer class per property calling the bean getter directly (no accessor, no index);
     * bean = one writer class per bean switching on the index and calling the getter directly;
     * beanser = "bean" plus a generated serializer per bean whose writer fields have the concrete
     * final writer type, so no call in the property sequence is megamorphic.
     */
    @Param({ "typed", "kind", "direct", "bean", "beanser" })
    public String writers;

    private ObjectWriter writer;
    private List<ExtendedPerson> people;
    private Sink out;

    @Setup
    public void setup() {
        Map<Class<?>, GeneratedPropertyAccessor> accessors = new HashMap<>();
        accessors.put(ExtendedPerson.class, new ExtendedPersonAccessor(ExtendedPerson.class));
        accessors.put(Address.class, new AddressAccessor(Address.class));
        accessors.put(Car.class, new CarAccessor(Car.class));
        SimpleModule module = new SimpleModule();
        module.setSerializerModifier("direct".equals(writers) ? new PerPropertyWriters.Modifier(accessors)
                : "bean".equals(writers) ? new PerBeanWriters.Modifier(accessors)
                : "beanser".equals(writers) ? new PerBeanSerializers.Modifier(accessors)
                : new GeneratedPropertyWriterModifier(accessors, "kind".equals(writers)));
        writer = QuarkusMapper.listWriter(QuarkusMapper.builder().addModule(module).build());
        ExtendedPerson person;
        if (strLen > 0) {
            String filler = "x".repeat(strLen);
            person = new ExtendedPerson(filler, filler, 30, new Address(filler, filler), new Car(filler, filler));
        } else {
            person = new ExtendedPerson("John", "Doe", 30, new Address("Gotham", "123 Main St"), new Car("Toyota", "Camry"));
        }
        people = Collections.nCopies(20, person);
        out = new Sink(1024 * 1024);
    }

    @TearDown
    public void tearDown() throws IOException {
        out.close();
    }

    @Benchmark
    @CompilerControl(CompilerControl.Mode.DONT_INLINE)
    public long serialize() throws IOException {
        out.reset();
        writer.writeValue(out, people);
        return out.count();
    }
}
